export const metadata = {
  title: 'Agenda Facil Naf',
  description: 'Generated by Next.js',

}
import{Roboto} from 'next/font/google'
const fontFamily = Roboto ({
  weight:["500","400","300"],
  subsets:['latin'],
  variable: '--font-family-main'
})
import "@/app/globals.css"
import { ThemeProvider } from '@/components/Provider/Theme-provider'
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={fontFamily.variable} suppressHydrationWarning>
      <head>
        <link rel="icon" type="image/png" href="https://www.unifeso.edu.br/images/favicon.png" />
      </head>
        <body className='bg-pagina dark:bg-pagina-dark transition-colors ease-in-out duration-200' >
          <ThemeProvider attribute="class" defaultTheme='system' enableSystem >
              {children}
          </ThemeProvider>
        </body>
    </html>
  )
}
