export const metadata = {
  title: 'Agenda Facil Naf',
  description: 'Generated by Next.js',

}
import{Roboto} from 'next/font/google'

const fontFamily = Roboto ({
  weight:["500","400","300"],
  subsets:['latin'],
  variable: '--font-family-main'
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={fontFamily.variable}>
      <head>
        <link rel="icon" type="image/png" href="https://www.unifeso.edu.br/images/favicon.png" />
      </head>
      <body >{children}</body>
    </html>
  )
}
